<a href="https://colab.research.google.com/github/jaysharma-ctrl/data-science-lab-exp001/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to NumPy

NumPy is an essential Python library. TensorFlow and scikit-learn use NumPy arrays as inputs, and pandas and Matplotlib are built on top of NumPy. In this Introduction to NumPy, you’ll become a master wrangler of NumPy’s core object: arrays! Using data from New York City’s tree census, you’ll create, sort, filter, and update arrays. You’ll discover why NumPy is so efficient and use broadcasting and vectorization to make your NumPy code even faster. By the end, you’ll be using 3D arrays to alter a Claude Monet painting, and you’ll understand why such array alterations are essential tools for machine learning.

#Understanding NumPy Arrays
Meet the incredible NumPy array! Learn how to create and change array shapes to suit your needs. Finally, discover NumPy’s many data types and how they contribute to speedy array operations.

#Introducing arrays
Your first NumPy array
Once you’re comfortable with NumPy, you’ll find yourself converting Python lists into NumPy arrays all the time for increased speed and access to NumPy’s excellent array methods.

`sudoku_list` is a Python list containing a sudoku game:

In [ ]:
sudoku_list = [[0, 0, 4, 3, 0, 0, 2, 0, 9],
                [0, 0, 5, 0, 0, 9, 0, 0, 1],
                [0, 7, 0, 0, 6, 0, 0, 4, 3],
                [0, 0, 6, 0, 0, 2, 0, 8, 7],
                [1, 9, 0, 0, 0, 7, 4, 0, 0],
                [0, 5, 0, 0, 8, 3, 0, 0, 0],
                [6, 0, 0, 0, 0, 0, 1, 0, 5],
                [0, 0, 3, 5, 0, 8, 6, 9, 0],
                [0, 4, 2, 9, 1, 0, 3, 0, 0]]

You’re going to change `sudoku_list` into a NumPy array so you can practice with it in later lessons, for example by creating a 4D array of sudoku games along with their solutions!

*   Import NumPy using its generally accepted alias.
*   Convert `sudoku_list` into a NumPy array called `sudoku_array`.
*   Print the class `type()` of `sudoku_array` to check that your code has worked properly.

In [ ]:
# Import NumPy
import numpy as np

# Convert sudoku_list into an array
sudoku_array = np.array(sudoku_list)

# Print the type of sudoku_array
print(type(sudoku_array))
print("Sudoku Array:\n", sudoku_array)

<class 'numpy.ndarray'>
Sudoku Array:
 [[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


##Creating arrays from scratch
It can be helpful to know how to create quick NumPy arrays from scratch in order to test your code. For example, when you are doing math with large multi-dimensional arrays, it’s nice to check whether the math works as expected on small test arrays before applying your code to the larger arrays. NumPy has many options for creating smaller synthetic arrays.

With this in mind, it’s time for you to create some arrays from scratch! `numpy` is imported for you as `np`.

*   Create and print an array filled with zeros called `zero_array`, which has two rows and four columns.
*   Create and print an array of random floats between `0` and `1` called `random_array`, which has three rows and six columns.




In [ ]:
# Create an array of zeros which has four columns and two rows


# Create an array of random floats which has six columns and three rows


##A range array
`np.arange()` has especially useful applications in graphing. Your task is to create a scatter plot with the values from `doubling_array` on the y-axis.

In [ ]:
doubling_array = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

Recall that a scatter plot can be created using the following code:


```
plt.scatter(x_values, y_values)
plt.show()
```


With `doubling_array` on the y-axis, you now need values for the x-axis, which you can create with `np.arange()`!

`numpy` is loaded for you as `np`, and `matplotlib.pyplot` is imported as `plt`.

In [ ]:
import numpy as np
from matplotlib import pyplot as plt

*   Using `np.arange()`, create a 1D array called `one_to_ten` which holds all integers from one to ten (inclusive).
*   Create a scatterplot with `doubling_array` as the y values and `one_to_ten` as the x values.

In [ ]:
# Create an array of integers from one to ten


# Create your scatterplot


#Array dimensionality
##3D array creation
In the first section, you created a `sudoku_game` two-dimensional NumPy array. Perhaps you have hundreds of sudoku game arrays, and you’d like to save the solution for this one, `sudoku_solution`, as part of the same array as its corresponding game in order to organize your sudoku data better. You could accomplish this by stacking the two 2D arrays on top of each other to create a 3D array.

`numpy` is loaded as `np`, and the `sudoku_game` and `sudoku_solution` arrays are available.

* Create a 3D array called `game_and_solution` by stacking the two 2D arrays, `sudoku_game` and `sudoku_solution`, on top of one another; in the final array, `sudoku_game` should appear before `sudoku_solution`.
* Print `game_and_solution`.

In [ ]:
sudoku_solution = np.array([[8, 6, 4, 3, 7, 1, 2, 5, 9],
                            [3, 2, 5, 8, 4, 9, 7, 6, 1],
                            [9, 7, 1, 2, 6, 5, 8, 4, 3],
                            [4, 3, 6, 1, 9, 2, 5, 8, 7],
                            [1, 9, 8, 6, 5, 7, 4, 3, 2],
                            [2, 5, 7, 4, 8, 3, 9, 1, 6],
                            [6, 8, 9, 7, 3, 4, 1, 2, 5],
                            [7, 1, 3, 5, 2, 8, 6, 9, 4],
                            [5, 4, 2, 9, 1, 6, 3, 7, 8]])
sudoku_game = np.array(sudoku_list)
print("suduko_game:\n",sudoku_game)
print("suduko_solution:\n",sudoku_solution)

suduko_game:
 [[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]
suduko_solution:
 [[8 6 4 3 7 1 2 5 9]
 [3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]


In [ ]:
# Create the game_and_solution 3D array


# Print game_and_solution


##The fourth dimension
Printing arrays is a good way to check code output for small arrays like `sudoku_game_and_solution`, but it becomes unwieldy when dealing with bigger arrays and those with higher dimensions. Another important check is to look at the array’s `.shape`.

Now, you’ll create a 4D array that contains two sudoku games and their solutions. `numpy` is loaded as `np`. The `game_and_solution` 3D array you created in the previous example is available, along with `new_sudoku_game` and `new_sudoku_solution`.

* Create another 3D array called `new_game_and_solution` with a different 2D game and 2D solution pair: `new_sudoku_game` and `new_sudoku_solution`. `new_sudoku_game` should appear before `new_sudoku_solution`.
* Create a 4D array called `games_and_solutions` by making an array out of the two 3D arrays: `game_and_solution` and `new_game_and_solution`, in that order.
* Print the shape of `games_and_solutions`.

In [ ]:
new_sudoku_game = np.array([[0, 0, 4, 3, 0, 0, 0, 0, 0],
                            [8, 9, 0, 2, 0, 0, 6, 7, 0],
                            [7, 0, 0, 9, 0, 0, 0, 5, 0],
                            [5, 0, 0, 0, 0, 8, 1, 4, 0],
                            [0, 7, 0, 0, 3, 2, 0, 6, 0],
                            [6, 0, 0, 0, 0, 1, 3, 0, 8],
                            [0, 0, 1, 7, 5, 0, 9, 0, 0],
                            [0, 0, 5, 0, 4, 0, 0, 1, 2],
                            [9, 8, 0, 0, 0, 6, 0, 0, 5]])
print(new_sudoku_game)

[[0 0 4 3 0 0 0 0 0]
 [8 9 0 2 0 0 6 7 0]
 [7 0 0 9 0 0 0 5 0]
 [5 0 0 0 0 8 1 4 0]
 [0 7 0 0 3 2 0 6 0]
 [6 0 0 0 0 1 3 0 8]
 [0 0 1 7 5 0 9 0 0]
 [0 0 5 0 4 0 0 1 2]
 [9 8 0 0 0 6 0 0 5]]


In [ ]:
new_sudoku_solution = np.array([[2, 5, 4, 3, 6, 7, 8, 9, 1],
                                [8, 9, 3, 2, 1, 5, 6, 7, 4],
                                [7, 1, 6, 9, 8, 4, 2, 5, 3],
                                [5, 3, 2, 6, 9, 8, 1, 4, 7],
                                [1, 7, 8, 4, 3, 2, 5, 6, 9],
                                [6, 4, 9, 5, 7, 1, 3, 2, 8],
                                [4, 2, 1, 7, 5, 3, 9, 8, 6],
                                [3, 6, 5, 8, 4, 9, 7, 1, 2],
                                [9, 8, 7, 1, 2, 6, 4, 3, 5]])
print(new_sudoku_solution)

[[2 5 4 3 6 7 8 9 1]
 [8 9 3 2 1 5 6 7 4]
 [7 1 6 9 8 4 2 5 3]
 [5 3 2 6 9 8 1 4 7]
 [1 7 8 4 3 2 5 6 9]
 [6 4 9 5 7 1 3 2 8]
 [4 2 1 7 5 3 9 8 6]
 [3 6 5 8 4 9 7 1 2]
 [9 8 7 1 2 6 4 3 5]]


Create another 3D array called `new_game_and_solution` with a different 2D game and 2D solution pair: `new_sudoku_game` and `new_sudoku_solution`. `new_sudoku_game` should appear before `new_sudoku_solution`

In [ ]:
# Create a second 3D array of another game and its solution


Create a 4D array called `games_and_solutions` by making an array out of the two 3D arrays: `game_and_solution` and `new_game_and_solution`, in that order.

In [ ]:
# Create a 4D array of both game and solution 3D arrays


Print the shape of `games_and_solutions`.

In [ ]:
# Print the shape of your 4D array


##Flattening and reshaping
You’ve learned to change not only array shape but also the number of dimensions that an array has. To test these skills, you’ll change `sudoku_game` from a 2D array to a 1D array and back again. Can we trust NumPy to keep the array elements in the same order after being flattened and reshaped? Time to find out.

Flatten `sudoku_game` so that it is a 1D array, and save it as `flattened_game`.

In [ ]:
# Flatten sudoku_game


Print the `.shape` of `flattened_game`.

In [ ]:
# Print the shape of flattened_game


Reshape the `flattened_game` back to its original shape of nine rows and nine columns; save the new array as `reshaped_game`.

In [ ]:
# Reshape flattened_game back to a nine by nine array


# Print sudoku_game and reshaped_game



##NumPy data types
The dtype argument
One way to control the data type of a NumPy array is to declare it when the array is created using the `dtype` keyword argument. Take a look at the data type NumPy uses by default when creating an array with `np.zeros()`. Could it be updated?

Using `np.zeros()`, create an array of zeros that has three rows and two columns; call it `zero_array`.

Print the data type of `zero_array`.


Create a new array of zeros called `zero_int_array`, which will also have three rows and two columns, but the data type should be `np.int32`.

Print the data type of `zero_int_array`.

In [ ]:
# Create an array of zeros with three rows and two columns


# Print the data type of zero_array





# Create a new array of int32 zeros with three rows and two columns




# Print the data type of zero_int_array




###Anticipating data types
Anticipating what data type an array will have is very important since some NumPy functionality only works with certain data types. Let’s see what you’ve got.

* For each of the given code snippets, determine which data type the resulting array will have by dragging the snippet to the proper box.

A string data type
```
np.array([78.988, "NumPy", True])
np.array([9, 1.12, True]).astype("<U5")
```
An integer data type
```
np.array([34.62, 70.13, 9]).astype(np.int64)
np.array([45.67, True], dtype=np.int8)
```
A float data type
```
np.array([[6, 15.7], [True, False]])
np.random.random((4, 5))
```

###A smaller sudoku game
NumPy data types, which emphasize speed, are more specific than Python data types, which emphasize flexibility. When working with large amounts of data in NumPy, it’s good practice to check the data type and consider whether a smaller data type is large enough for your data, since smaller data types use less memory.

It’s time to make your sudoku game more memory-efficient using your knowledge of data types! `sudoku_game` has been loaded for you as a NumPy array. numpy is imported as np.

* Print the data type of the elements in `sudoku_game`.

In [ ]:
# Print the data type of sudoku_game


The current data type of `sudoku_game` is `int64`.
* Which of the following NumPy integers is the smallest bitsize that is still large enough to hold the data in `sudoku_game`?
* If you have never played sudoku, know that sudoku games only ever store integers from one to nine.
** np.int64
** np.int32
** np.int16
** np.int8

Change the data type of `sudoku_game` to be `int8`, an 8-bit integer; name the new array `small_sudoku_game`.



Print the data type of `small_sudoku_game` to be sure that your change to `int8` is reflected.

#Selecting and Updating Data
Sharpen your NumPy data wrangling skills by slicing, filtering, and sorting New York City’s tree census data. Create new arrays by pulling data based on conditional statements, and add and remove data along any dimension to suit your purpose. Along the way, you’ll learn the shape and dimension compatibility principles to prepare for super-fast array math.

##Indexing and slicing arrays
###Slicing and indexing trees
Imagine you are a researcher working with data from New York City’s tree census. Each row of the `tree_census` 2D array lists information for a different tree: the tree ID, block ID, trunk diameter, and stump diameter in that order. Living trees do not have stump diameters, which explains why there are so many zeros in that column. Column order is important because NumPy does not have column names! The first and last three rows of `tree_census` are shown below.

In [ ]:
import pandas as pd
tree_census = pd.read_csv("https://data.cityofnewyork.us/api/views/uvpi-gqnh/rows.csv?accessType=DOWNLOAD")

In [ ]:
tree_census = pd.DataFrame(tree_census)

In [ ]:
tree_census.head()

In [ ]:
tree_census = tree_census[["tree_id","block_id","tree_dbh","stump_diam"]]

In [ ]:
tree_census.head()

In [ ]:
tree_census = np.array(tree_census)

In [ ]:
print(tree_census)

In this exercise, you’ll be working specifically with the second column, representing block IDs: your research requires you to select specific city blocks for further analysis using NumPy slicing and indexing. `numpy` is loaded as `np`, and the `tree_census` 2D array is available.

Select all rows of data from the second column, representing block IDs; save the resulting array as `block_ids`.

In [ ]:
# Select all rows of block ID data from the second column



Print the first five block IDs from `block_ids`.

In [ ]:
# Print the first five block_ids


Select the tenth block ID from `block_ids`, saving the result as `tenth_block_id`.

In [ ]:
# Select the tenth block ID from block_ids


Select five consecutive block IDs from `block_ids`, starting with the tenth ID, and save as `block_id_slice`

In [ ]:
# Select five block IDs from block_ids starting with the tenth ID


###Stepping into 2D
Now assume that your research requires you to take an admittedly unrepresentative sample of trunk diameters, which are located in the third column of tree_census. Getting just a selection of trunk diameters can be done with NumPy’s slicing and stepping functionality.


numpy is loaded as np, and the tree_census 2D array is available.

Create an array called hundred_diameters which contains the first 100 trunk diameters in tree_census.

Create an array,every_other_diameter, which contains only trunk diameters for trees with even row indices from 50 to 100, inclusive.

# Sorting trees
Sometimes it’s easiest to understand data when it is sorted according to the value you are most interested in. Your new research task is to create an array containing the trunk diameters in the New York City tree census, sorted in order from smallest to largest.

* `numpy` is loaded as `np`, and the `tree_census` 2D array is available.

Create an array called `sorted_trunk_diameters` which selects only the trunk diameter column from `tree_census` and sorts it so that the smallest trunk diameters are at the top of the array and the largest at the bottom.


In [ ]:
# Extract trunk diameters information and sort from smallest to largest
